[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rhysd/wandbox-vim'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo = 'justmao945/vim-clang'
if = "!has('nvim')"
on_ft = ['c', 'cpp']
hook_add = '''
" disable auto completion for vim-clang
let g:clang_auto = 0

" default 'longest' can not work with neocomplete
let g:clang_c_completeopt   = 'menuone'
let g:clang_cpp_completeopt = 'menuone'

let g:clang_exec = 'clang'
let g:clang_format_exec = 'clang-format'
let g:clang_c_options = '-std=c11'
let g:clang_cpp_options = '-std=c++1z -stdlib=libc++'
'''

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'html'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'moznion/hateblo.vim'
depends = 'webapi-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive', 'vim-gitgutter']
hook_add = 'source ~/.vim/rc/plugins/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_source = '''
  let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'
hook_source = '''
  let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
hook_source = '''
  let g:comfortable_motion_no_default_key_mappings = 1
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

