[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rhysd/wandbox-vim'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo = 'justmao945/vim-clang'
if = "!has('nvim')"
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'html'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'moznion/hateblo.vim'
depends = 'webapi-vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-fugitive', 'vim-gitgutter']

[[plugins]]
repo = 'itchyny/vim-parenmatch'
hook_source = '''
  let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'
hook_source = '''
  let g:loaded_matchparen = 1
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'
hook_source = '''
  let g:comfortable_motion_no_default_key_mappings = 1
'''

