[[plugins]]
repo = 'Shougo/neocomplete.vim'
depends = 'context_filetype.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
#  source ~/.vim/rc/plugins/neocomplete.rc.vim
'''

#[[plugins]]
#repo = 'zchee/deoplete-clang'
#on_ft = ['c', 'cpp']
#
#[[plugins]]
#repo = 'zchee/deoplete-jedi'
#on_ft = 'python'
#
#[[plugins]]
#repo = 'zchee/deoplete-go'
#on_i = 1
#on_ft = 'go'
#
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#depends = 'context_filetype.vim'
#if = "has('nvim')"
#on_i = 1
#hook_source = '''
#  let g:deoplete#enable_at_startup = 1
##  source ~/.vim/rc/plugins/deoplete.rc.vim
#'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
# hook_source = 'source ~/.vim/rc/plugins/neosnippet.rc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'kana/vim-altr'

